source = ~/.config/hypr/monitors_custom.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/workspace.conf

input {
  # kb_layout = en
  numlock_by_default = true
  repeat_delay = 150
  repeat_rate = 50

  follow_mouse = 1
  off_window_axis_events = 2

  touchpad {
    natural_scroll = no
    disable_while_typing = true
    clickfinger_behavior = true
    tap-to-click = false
    scroll_factor = 0.4
  }
}

